version: "3.9"

services:
  discord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord
    depends_on:
      - postgres
    volumes:
      - "./src:/app/src"
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db:
